### PR TITLE
[RFC] Improve performance

### PR DESCRIPTION
**Pull request by aengelke**
Profiling indicates that the fuzzer spends a lot of time with synchronization. I rewrote the fuzzer to use more lightweight synchronization primitives (plain atomics + futex). This massively increases throughput in the range of 20-40x (times, not percent). This necessitates putting simple filters (min/max success and ndecoded differences) directly into the fuzzer -- otherwise the output and analysis time would dominate.

The following things are not implemented right now:

- ~~Crash handling. In pthread-mode, this currently brings down the entire fuzzer; in fork-mode, handling could be implemented. I didn't encounter crashed so far, so I didn't consider this as too important.~~ Update: this should now work (if the crash happens during decoding and children are forked off).
- Non-Linux/glibc support. Esp. futexes are Linux-only; naive spinlock synchronization works, but is highly inefficient (>2x slowdown, depending on core and worker count).
- Normalization. Some changes (e.g., to lower/whitespace unification) should probably be done in C, too.

I'm not sure you want to merge this (and probably not in this state, anyway), but I thought you might be interested -- and wanted to ask whether this approach has any chances to be merged at all after some further work.

(I also have a (very WIP) [analysis script](https://gist.github.com/aengelke/4223eba3fdffa9a3b6383a84636dca94) which does a more extensive text-based normalization (and deduplication that ignores the actual register values) to find discrepancies in the decoded text (e.g. operand sizes, register names, immediate values, rounding mode, etc.). That's quite different from the existing infrastructure, so again I'm very unsure whether that'd fit for this project.)

### CODE REVIEW

**Comment by woodruffw** [comment]
20-40x is pretty incredible! I knew my shm/semaphore-based implementation wasn't the fastest, but that's quite impressive 🙂 

I'll do a detailed review later, but generally speaking: I'm more than happy to merge significant changes to mishegos's core in the interests of performance.

I'm also open to changes to the analysis scripts/overall structure there -- it's currently a little overengineered because of grand plans I had for LLVM-style analysis passes, and could definitely be made simpler/faster/more effective.

**Comment by aengelke** [comment]
Thanks! :) -- I think this is ready for a first review now.

Handling crashing decoders should work now -- at least, I couldn't think of any more race conditions to occur and it runs smoothly for >1k runs with a crash-test dummy decoder. I'll keep analysis changes for a later point when its ready. I can't test non-Linux systems due to a lack of hardware, but [this article](https://shift.click/blog/futex-like-apis/) describes some alternatives to futexes on other systems.

**Comment by woodruffw** [comment]
> Thanks! :) -- I think this is ready for a first review now.

Awesome! Thanks a ton again for doing this.

Sorry for the delay here -- I should have time for a full review early next week 🙂

**Comment by aengelke** [comment]
I was curious how good this implementation is, so I did some benchmarking on my (fairly old) machine (Core i5-5250U, 2 cores/4 threads). tl;dr: it comes close to 90% of "optimal" performance and gives a speed up of 7-100x compared to current master.

As a consequence of the functional parallelism with workers, the slowest worker limits the overall throughput (given enough cores). So I benchmarked the time each workers individually needs to emit 10M samples, without including mutation/output time, to find the upper bound:

Individual workers

Note that Ghidra is by far the slowest worker, taking ~23s for 10M samples, followed by XED with ~12s. yaxpeax takes 2.27s and Fadec 0.84s.

Running a single worker in mishegos (this PR) with forking and synchronization adds a slight overhead:

bench2

It becomes clear that old Mishegos limited the worker throughput when doing the same experiment on current master (modified to not output anything and terminate after 10M samples):

bench2old



I also compared against a single-threaded version ("sequential"), which runs all workers sequentially in a single process (so no synchronization involved). Running this in n times parallel producing 1/n samples each ("parallel runs") should give the optimal throughput as all cores are constantly utilized and no synchronization overhead exists. The comparison to this data-parallel approach is the functionally-parallel approach with one task per worker and synchronization ("parallel workers"). I did one run with the two fastest workers (as the machine has just two cores) and one run with the four fastest workers (using all 4 threads). For comparison, the old Mishegos implementation (current master, modified to not output anything and terminate after 10M samples) is included.

bench3

Due to synchronization and slight overcommitting (2 parallel workers = 3 processes), the worker-parallel of this PR approach comes just close to the optimal setup (which doesn't give any isolation between workers). Not using parallelism at all for a low number of workers appears to be faster than the implementation on current master -- particularly in the contended case of having more processes than cores.

Unfortunately, I didn't get around yet to benchmark this on a machine with more cores.

**Review by woodruffw — APPROVED** [review]
LGTM! I'm always happy to merge a huge deletion, especially when it's of terribly (and prematurely) optimized concurrency code 🙂

**Pull request merged**
