### PR TITLE
Add a Fadec worker

### PR DESCRIPTION
**Pull request by aengelke**
Add a worker for [Fadec](https://github.com/aengelke/fadec) (which is a decoder I wrote/maintain). I'm not entirely sure whether that fits the scope of this project. Anyway, it is probably the smallest x86 decoder out there with ~45k library size...

In fact, I used Mishegos to fix several bugs, so thanks for doing the work and publishing it!

### CODE REVIEW

**Comment by woodruffw** [comment]
Looks like an include directory issue?

```
In file included from fadec.c:1:0:

fadec/fadec.h:34:10: fatal error: fadec-decode-table.inc: No such file or directory

 #include <fadec-decode-table.inc>

          ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by aengelke** [comment]
It was a dependency issue, where a generated header was not yet built. Should be fixed now.

**Comment by woodruffw** [comment]
Gotcha, thanks. I'll take another look later today!

**Comment by woodruffw** [comment]
LGTM! Sorry for the delay, will merge in a bit.

**Pull request merged**
